function(common_options_scope)
	set(LIB_NAME ${PROJECT_NAME}_common_options)
	add_library(${LIB_NAME} INTERFACE)
	target_compile_features(${LIB_NAME} INTERFACE cxx_std_20)
	set_target_properties(${LIB_NAME} PROPERTIES EXPORT_NAME common_options)
	add_library(${PROJECT_NAME}::common_options ALIAS ${LIB_NAME})
	install(TARGETS ${LIB_NAME} EXPORT ${EXPORT_FILE})
endfunction()
common_options_scope()
